### ISSUE TITLE
Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by gundermanc** [BigEggTools/PowerMode#1]
InvalidOperationException is sometimes thrown by the 'NewParticlesImage' method when typing and the caret is off screen due to the following line:

            var top = view.Caret.Top;

To fix this, you should wrap this call in:

            if (view.Caret.IsVisible)
            {
            ...
            }

Fixes an error dialog box.

**Comment by BigEgg** [comment]
Thanks, will fix this shortly

**Comment by BigEgg** [comment]
Didn't find the **isVisible** property in the Caret (ITextView interface). Probably this is because of the .Net Framework version.

Still Add the try catch block for it to make sure this will not cause any exception anymore
