### ISSUE TITLE
No screen shake

### ISSUE THREAD

**Issue by CRodriguez25** [BigEggTools/PowerMode#10]
When installed locally in VS2017 or VS2019, no screen shake occurs when typing

**Comment by BigEgg** [comment]
@CRodriguez25 May I know the repo steps?

By default, when **Combo Mode** is enabled, **Screen Shake** won’t appear until reach the activation threshold. 

And you can update the settings in the Combo Mode options panel for the Screen Shake start threshold.

**Comment by CRodriguez25** [comment]
Yeah I closed this issue because I discovered that combo threshold almost immediately after posting this issue. Very sorry!

I'm also not able to change the particle "Color Type" from "Random". It seems like that dropdown is disabled. Am I missing something obvious again?

Either way, sorry to bother you and thanks for this really nice extension!

**Comment by BigEgg** [comment]
Oh, for that, accurately I didn't add the other logic at this time. 

It should have other 2 options:
* **Current Cursor Color**, however, It's hard to get the current color in the Editor
* **Fixed Color**, I think it is not that fun, so just didn't add that one yet, but I created the task #11  to trace it.
