### ISSUE TITLE
Combo text is small and blur with light background

### ISSUE THREAD

**Issue by heroboy** [BigEggTools/PowerMode#12]
![图片](https://user-images.githubusercontent.com/54468/56713870-9cb55c80-6765-11e9-9f56-38fb3d0f207b.png)
Zoom in, still blur
![图片](https://user-images.githubusercontent.com/54468/56713889-af2f9600-6765-11e9-8a42-d813a59e6938.png)

**Comment by BigEgg** [comment]
Oh, I think this is shows that this extension is not work very well in the white theme, will take a look, thanks for let me know this

**Comment by BigEgg** [comment]
Use the RBG average from background as a flag for title color

**Comment by BigEgg** [comment]
![image](https://user-images.githubusercontent.com/1243699/94499484-af7d5d80-01b1-11eb-8324-b603c77cbce6.png)
This will be the effect when background is in light color
