### ISSUE TITLE
Count incorrect during Raname(Refactor)

### ISSUE THREAD

**Issue by sgkoishi** [BigEggTools/PowerMode#3]
When using Ctrl+R, Ctrl+R to rename a variable, PowerMode count typing for every changed variable when they were changed by IDE, cause lag and incorrect number.

**Comment by BigEgg** [comment]
Thanks for letting me know this, will fix it shortly.
It's being a while i didn't working on this project, but I believe now is a good time to doing the fixing and prepare for the Visual Studio 2019

**Comment by BigEgg** [comment]
I tested it and didn't see this comes in the newer version~~

I'll close this issue right now, if there have any change that happened again, please let me know the repo step, so I can try to fix it again.

Thanks
