### ISSUE TITLE
Support VS 2022

### ISSUE THREAD

**Issue by JiaChen-Zeng** [BigEggTools/PowerMode#35]
Can't write code without the POWER anymore! Please support VS 2022.

**Comment by JiaChen-Zeng** [comment]
This extension just works on VS 2022. I manually installed it and didn't see any problem for now. Just unzip the extension pack and copy the files into `%localappdata%\Microsoft\VisualStudio\17.0_da8b3f8c\Extensions`.

For this issue, I think it only needs to specify it supports VS 2022 so we can install it directly from the marketplace.

**Comment by BigEgg** [comment]
Thanks for loving PowerMode.

Good to know that the code is already supported VS 2022, in that case can you please sent an PR to
* update the `source.extension.vsixmanifest` file for supporting new VS version?
* also update the `PowerModePackage.cs` file for bumping the version to 1.1?

I will try to find some place to compile it and upload the new version

**Comment by MrClyfar** [comment]
Would love for this extension to be VS2022 compatible.

**Comment by craftercis** [comment]
I can't get it working on VS Studio 2022.

**Comment by MrClyfar** [comment]
It looks like we can get a VS 2022 compatible version e.g.

[Add support for VS2022](https://github.com/BigEggTools/PowerMode/pull/37)

but this PR has not been merged yet.

Hopefully @BigEgg will get the opportunity to do so. Please, please, please @BigEgg  :)

**Comment by BigEgg** [comment]
Thanks for your interest in this project!

I just checked the PR and found it updated the VSSDK and target framework version. So I think this might break the usage for the early version of Visual Studio.

Can you please help me to update it or test it out on the earlier version of VS?

**Comment by BigEgg** [comment]
I merged https://github.com/BigEggTools/PowerMode/pull/37. Thanks, @tomfrenzel!

Sadly, I don't have a Windows PC in my nearby. So can any of you help me to create a RELEASE build version and attach it here? I will update it to the **VS marketplace** and the **Release** tab in Github.

**Comment by tomfrenzel** [comment]
Hey @BigEgg!
here is the output of my release build: [Release.zip](https://github.com/BigEggTools/PowerMode/files/9153926/Release.zip)

**Comment by BigEgg** [comment]
Uploaded the new version that supports VS 2022!

**Comment by tomfrenzel** [comment]
Hello @BigEgg!

I saw you made some changes to the code and published a new release. Unfortunately, the extension is now only compatible with the first version of VS2022 (and older VS versions) since its version number is 17.0. Any newer release won't be able to install the Plugin because its Version number is greater than 17.0 [see here](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2022).

It should be `[17.0,18.0)` so every VS2022 release will be included but the next major one not.

Could you please correct the version number and re-release the extension?

**Comment by BigEgg** [comment]
sure, let me update it and publish a newer version

**Comment by MrClyfar** [comment]
Thanks to both of you for making this happen so quickly 👍
