### ISSUE TITLE
Not That Great Exception Being Thrown In VS 2017

### ISSUE THREAD

**Issue by d-h-morrison** [BigEggTools/PowerMode#4]
Seems to be a fairly random exception.  Here it is for what it's worth.
==============

System.InvalidOperationException: GetTextViewLineContainingBufferPosition called after the view is closed   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Microsoft.VisualStudio.Text.Editor.IWpfTextView.GetTextViewLineContainingBufferPosition(SnapshotPoint bufferPosition)   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.GetTextViewLineContainingBufferPosition(SnapshotPoint bufferPosition)   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.SelectionUIProperties.get_ContainingTextViewLine()   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.SelectionUIProperties.get_CaretBounds()   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.get_Top()   at BigEgg.Tools.PowerMode.Adornments.ParticlesAdornment.NewParticlesImage(IAdornmentLayer adornmentLayer, IWpfTextView view) in D:\BigEgg\Tools\PowerMode\PowerMode\Adornments\ParticlesAdornment.cs:line 69   at BigEgg.Tools.PowerMode.Adornments.ParticlesAdornment.OnTextBufferChanged(IAdornmentLayer adornmentLayer, IWpfTextView view, Int32 streakCount) in D:\BigEgg\Tools\PowerMode\PowerMode\Adornments\ParticlesAdornment.cs:line 57   at BigEgg.Tools.PowerMode.PowerModeAdornment.TextBuffer_Changed(Object sender, TextContentChangedEventArgs e) in D:\BigEgg\Tools\PowerMode\PowerMode\PowerModeAdornment.cs:line 93   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--

**Comment by d-h-morrison** [comment]
… And the other thing that's not that great about this is that after the error is thrown, VS 2017's performance is degraded and is for s**t.  So you need to shut down and restart.  This makes it super hard to use, esp. if this happens a lot, but Power mode is a cool extension, so it's almost worth it, … um, yeah, sort of.

**Comment by BigEgg** [comment]
Thanks for letting me know this, will fix it shortly.
It's being a while i didn't working on this project, but I believe now is a good time to doing the fixing and prepare for the Visual Studio 2019

**Comment by BigEgg** [comment]
Also I have notice it will throw exception in some other scenario, and already find the repo step, so will fix them together.

**Comment by BigEgg** [comment]
I tested it and didn't see this comes in the newer version~~
But I still add a try/catch block in that area where this exception raise, hopefully this will not happened again.

I will close this issue now, if there have any change that happened again, please let me know the repo steps, so I can try fix it.

Thanks

**Comment by BigEgg** [comment]
I think this is related with #1 and since I already update it in the code but never release it. That might cause this issue. Please update this extension to v0.6 (just release it today) to check if there has any exception raise again.
