### ISSUE TITLE
Improving the responsiveness of critical scenarios by updating auto load behavior for extensions

### ISSUE THREAD

**Issue by BigEgg** [BigEggTools/PowerMode#6]
When using the ProvideAutoLoad attribute, your package (BigEgg.Tools.PowerMode.PowerModePackage) class should derive from AsyncPackage instead of Package to improve performance. Read more about using AsyncPackage here: https://aka.ms/asyncpackage.

- [x] Test in VS 2017
- [x] Test in VS 2019

**Comment by BigEgg** [comment]
https://devblogs.microsoft.com/visualstudio/updates-to-synchronous-autoload-of-extensions-in-visual-studio-2019/
According to this document, start from 16.1, this extension will be blocked since it use synchronous auto load.
Should update this asap.

**Comment by yanshouwang** [comment]
Any progress for this?

**Comment by BigEgg** [comment]
Created feature/async-package branch to fix this.
Reference: [AsyncPackageMigration](https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration)

**Comment by BigEgg** [comment]
@yanshouwang Will build and upload the binary tomorrow.
